import { Scores } from "../types/index";



export function generate(scores: Scores): string {
    const { idiomScore, complexityScore, abstractionScore, 
        errorHandlingScore, modernSyntaxScore, 
        finalScore ,level} = scores;
    let claudeInstructions = '';
    
    // HEADER
    claudeInstructions += '## Purpose \nThis file was generated by fence-vscode.';
    claudeInstructions += 'This extension supports TS and JS overview of your code quality';
    
    // Skill Level
    claudeInstructions += `\n## Your Skill Level\nOverall: ${scores.level} (${scores.finalScore}/10)`;

    const WARN_THRESHOLD = 0.6;
    const dimensionScores = {
        idiomScore,
        complexityScore,
        abstractionScore,
        errorHandlingScore,
        modernSyntaxScore,
    } as const;

    const dimensionLabels: Record<keyof typeof dimensionScores, string> = {
        idiomScore:         'Idiomatic Usage',
        complexityScore:    'Complexity',
        abstractionScore:   'Abstraction',
        errorHandlingScore: 'Error Handling',
        modernSyntaxScore:  'Modern Syntax',
    };

    claudeInstructions += '\n\n## Dimension Scores';
    for (const [key, value] of Object.entries(dimensionScores) as [keyof typeof dimensionScores, number][]) {
        const pct     = Math.round(value * 100);
        const warning = value < WARN_THRESHOLD ? ' ⚠' : '';
        claudeInstructions += `\n- ${dimensionLabels[key]}: ${pct}%${warning}`;
    }

    
    // Area to improve
    const areasToImprove = (Object.entries(dimensionScores) as [keyof typeof dimensionScores, number][])
        .filter(([_, value]) => value < WARN_THRESHOLD)
        .map(([key]) => dimensionLabels[key]);

    if (areasToImprove.length > 0) {
        claudeInstructions += '\n\n## Area to Improve';
        areasToImprove.forEach(label => {
            claudeInstructions += `\n- ${label}`;
        });
    }

    // CLAUDE BEHAVIOR RULES
    const levelRules: Record<typeof level, { depth: string; style: string }> = {
        beginner: {
            depth: '- Explain every concept fully. Assume no prior knowledge. Use analogies and plain language.',
            style: '- Do not write code directly. Guide with hints, targeted questions, and small examples.',
        },
        elementary: {
            depth: '- Cover core concepts briefly. Introduce patterns with simple examples.',
            style: '- Show small corrected snippets with a one-line explanation per change.',
        },
        intermediate: {
            depth: '- Skip fundamentals. Briefly explain non-obvious decisions. Focus on the "why" behind the fix.',
            style: '- Provide corrected code with concise inline comments on what changed and why.',
        },
        advanced: {
            depth: '- Omit explanations unless explicitly asked. Use precise technical language.',
            style: '- Provide corrected code only. Add comments solely when the fix is non-obvious.',
        },
        expert: {
            depth: '- No explanations. Assume full language and ecosystem mastery.',
            style: '- Flag issues by name only (e.g. "N+1", "missing invariant"). Skip obvious fixes.',
        },
    };

    const { depth, style } = levelRules[level];

    const responseStyle = areasToImprove.length === 0
        ? '- All dimensions are strong. Suggest optimizations and best practices only.'
        : `- Weak areas detected: ${areasToImprove.join(', ')}. Prioritize feedback on these.\n${style}`;

    claudeInstructions += '\n\n## Behavior Rules';
    claudeInstructions += `\nYou are reviewing code written by a ${level} developer. Adhere to the following:`;
    claudeInstructions += `\n\n### Explanation Depth\n${depth}`;
    claudeInstructions += `\n\n### Response Style\n${responseStyle}`;
        
    return claudeInstructions;
}

// const args = {idiomScore: 0.8, complexityScore: 0.5, abstractionScore: 0.7, errorHandlingScore: 0.2, modernSyntaxScore: 0.8, finalScore: 7, level: 'intermediate' as const};
// console.log(generate(args));