import { Skill, SkillLevel } from '../types';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function confidenceLabel(c: number): string {
    if (c >= 90) {return 'Expert';}
    if (c >= 75) {return 'Proficient';}
    if (c >= 60) {return 'Comfortable';}
    if (c >= 40) {return 'Familiar';}
    return 'Exploring';
}

function groupByLanguage(skills: Skill[]): Map<string, Skill[]> {
    const map = new Map<string, Skill[]>();
    for (const s of skills) {
        const list = map.get(s.language) ?? [];
        list.push(s);
        map.set(s.language, list);
    }
    return map;
}

// ---------------------------------------------------------------------------
// Generator
// ---------------------------------------------------------------------------

/**
 * @param skills        Full skill list loaded from the store.
 * @param stressedSkills  Skill names that currently have active diagnostic
 *                        errors in the editor. These are forced into the
 *                        "Still Learning" section regardless of stored score.
 */
export function generate(skills: Skill[], stressedSkills: Set<string> = new Set()): string {
    if (skills.length === 0) {
        return `## Purpose\n\nNo skills detected yet. Run \`fence init\` inside a project directory.\n`;
    }

    // Force any skill under active diagnostic pressure to Learning level
    const adjusted = skills.map(s =>
        stressedSkills.has(s.name)
            ? { ...s, level: SkillLevel.Learning }
            : s,
    );

    const known    = adjusted.filter(s => s.level === SkillLevel.Knows);
    const learning = adjusted.filter(s => s.level === SkillLevel.Learning);

    const knownByLang    = groupByLanguage(known);
    const learningByLang = groupByLanguage(learning);

    // ── Known section ──────────────────────────────────────────────────────
    let knownSection = '';
    for (const [lang, list] of knownByLang) {
        knownSection += `\n### ${lang}\n`;
        for (const s of list.sort((a, b) => b.confidence - a.confidence)) {
            knownSection += `- ${s.name} *(${confidenceLabel(s.confidence)})*\n`;
        }
    }

    // ── Learning section ───────────────────────────────────────────────────
    let learningSection = '';
    for (const [lang, list] of learningByLang) {
        learningSection += `\n### ${lang}\n`;
        for (const s of list.sort((a, b) => b.confidence - a.confidence)) {
            const stressNote = stressedSkills.has(s.name) ? ' *(active errors)*' : '';
            learningSection += `- ${s.name}${stressNote}\n`;
        }
    }

    // ── Learning-specific rules ────────────────────────────────────────────
    const learningNames    = learning.map(s => `**${s.name}**`).join(', ');
    const learningRulesBlock = learning.length > 0
        ? `## Rules for Skills I'm Learning

The following skills appear in my code but I haven't yet mastered them:
${learningNames}

For any of these:
1. Explain the concept — what it is and why it exists
2. Give a guiding question or minimal hint
3. Let me write the code
4. Only after I've written it, help me fix or improve it

If I ask you to "just write it", push back and ask what part I'm stuck on instead.
`
        : '';

    return `## Purpose

This file was generated by **fence** — it maps my demonstrated coding skills so Claude
can calibrate its responses to my actual knowledge level.

## What I Already Know
${knownSection || '\n*(none detected yet)*\n'}
## What I'm Still Learning
${learningSection || '\n*(none detected yet)*\n'}
${learningRulesBlock}## Rules for Claude

**Match my level — do not use patterns absent from "What I Already Know".**

**You may freely:**
- Fix syntax errors in code I've written
- Explain concepts in plain terms
- Review and correct code I've already written
- Use patterns from "What I Already Know" when filling in small gaps

**You must not:**
- Generate boilerplate or scaffold files on my behalf using skills I'm still learning
- Complete API calls or implementations I haven't started for learning-stage skills
- Write working implementations of skills listed under "Still Learning"

**Confidence levels** indicate how often a pattern appears in my code:
Exploring < Familiar < Comfortable < Proficient < Expert
`;
}
