import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';
import type { SkillProfile } from './types/index';

// ── Construct labels ───────────────────────────────────────────────────────
// Maps internal construct names → human-readable descriptions for CLAUDE.md.
// Fallback: raw name is used if a label is missing.

const CONSTRUCT_LABELS: Record<string, string> = {
  // Tier 1
  basicTypes:           'Basic type annotations (string, number, boolean, void)',
  simpleInterfaces:     'Simple interfaces and type aliases',
  typedFunctions:       'Typed function parameters and return types',
  // Tier 2
  unionTypes:           'Union types (string | number, A | B)',
  consumingGenerics:    'Consuming generics (Array<T>, Promise<void>, Map<K, V>)',
  optionalChaining:     'Optional chaining (a?.b?.c)',
  nullishCoalescing:    'Nullish coalescing (a ?? b)',
  destructuring:        'Destructuring (const { x } = obj, const [a] = arr)',
  // Tier 3
  arrayMethods:         'Array methods (.map, .filter, .reduce, .find)',
  asyncAwait:           'async/await',
  writingGenerics:      'Writing generic functions (function foo<T>(x: T): T)',
  typeGuards:           'Type guards (x is SomeType return annotation)',
  utilityTypes:         'Utility types (Partial, Pick, Omit, Record, ReturnType)',
  discriminatedUnions:  'Discriminated unions (type Shape = Circle | Square)',
  higherOrderFns:       'Higher-order functions',
  // Tier 4
  conditionalTypes:     'Conditional types (T extends U ? X : Y)',
  mappedTypes:          'Mapped types ({ [K in keyof T]: T[K] })',
  constrainedGenerics:  'Constrained generics (<T extends keyof U>)',
  inferKeyword:         'infer keyword (T extends Promise<infer U> ? U : never)',
  templateLiteralTypes: 'Template literal types (`on${string}`)',
  // Tier 5
  recursiveTypes:       'Recursive types (type JSON = string | JSON[])',
  varianceAnnotations:  'Variance annotations (in/out modifiers on generics)',
};

const TIER_NAMES: Record<number, string> = {
  1: 'Novice',
  2: 'Elementary',
  3: 'Intermediate',
  4: 'Advanced',
  5: 'Expert',
};

// ── Public API ─────────────────────────────────────────────────────────────

// CLAUDE.md always lives in the workspace .fence/ so Claude Code can find it,
// regardless of where profile.json and other data files are stored.
export function generateClaudeMd(profile: SkillProfile): void {
  const root = vscode.workspace.workspaceFolders?.[0]?.uri.fsPath;
  if (!root) return;

  const fenceDir = path.join(root, '.fence');
  if (!fs.existsSync(fenceDir)) {
    fs.mkdirSync(fenceDir, { recursive: true });
  }

  fs.writeFileSync(path.join(fenceDir, 'CLAUDE.md'), buildContent(profile), 'utf8');
}

// ── Template ───────────────────────────────────────────────────────────────

function buildContent(profile: SkillProfile): string {
  const tierName = TIER_NAMES[profile.tier] ?? String(profile.tier);
  const score    = profile.scores.finalScore.toFixed(1);
  const date     = profile.lastUpdated.slice(0, 10);

  const knownList   = toList(profile.knownConstructs);
  const unknownList = toList(profile.unknownConstructs);

  const rules = profile.mode === 'assist'
    ? `- ONLY generate code using constructs from the "Known" list above
- If a task requires an "Unknown" construct, use the simplest known alternative instead
- Never use an unknown construct — no explanation needed, just stay within the known list`
    : `- ONLY generate code using constructs from the "Known" list above
- If a task requires an "Unknown" construct, EXPLAIN the concept first
- Ask the user to write it themselves after explaining
- Never silently use an unknown construct in generated code`;

  return `# fence-vscode Skill Context

This file is auto-generated by fence-vscode. Do not edit manually.

## Developer Skill Profile

**Tier:** ${profile.tier} (${tierName})
**Score:** ${score} / 10
**Mode:** ${profile.mode}
**Last scanned:** ${date}

## Known Constructs (safe to generate)

${knownList}

## Unknown Constructs (DO NOT generate — teach instead)

${unknownList}

## Rules

${rules}
`;
}

function toList(constructs: string[]): string {
  if (constructs.length === 0) return '_(none)_';
  return constructs
    .map(c => `- ${CONSTRUCT_LABELS[c] ?? c}`)
    .join('\n');
}
